---
name: Run CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

# If another push to the same PR or branch happens while this workflow is still running,
# cancel the earlier run in favor of the next run.
#
# There's no point in testing an outdated version of the code. GitHub only allows
# a limited number of job runners to be active at the same time, so it's better to cancel
# pointless jobs early so that more useful jobs can run sooner.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  POETRY_VERSION: "1.7.1"
  WORKDIR: "."

jobs:
  lint:
    uses:
      ./.github/workflows/_lint.yml
    with:
      working-directory: .
    secrets: inherit
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    name: Python ${{ matrix.python-version }} tests
    steps:
      - name: Add hosts to /etc/hosts
        shell: bash
        run: sudo echo "127.0.0.1 mariadb.example.com" | sudo tee -a /etc/hosts
      - uses: getong/mariadb-action@v1.11
        with:
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_general_ci'
          mariadb version: '11.7-rc'
          mysql database: 'langchain'
          mysql root password: 'langchain'
          mysql user: 'langchain'
          mysql password: 'langchain'
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          working-directory: ${{ env.WORKDIR }}
          cache-key: langchain-extract-all
      - name: Test database connection
        run: |
          # Set up mariadb-client
          sudo apt-get install -y libmariadb3 libmariadb-dev
      - name: Install dependencies
        shell: bash
        run: |
          echo "Running tests, installing dependencies with poetry..."
          poetry install --with test,lint,typing,docs
      - name: Run tests
        run: make test
        env:
          MARIADB_HOST: mariadb.example.com
          MARIADB_USER: root
          MARIADB_PASSWORD: langchain
          MARIADB_ROOT_PASSWORD: langchain
          MARIADB_DATABASE: langchain
      - name: Ensure the tests did not create any additional files
        shell: bash
        run: |
          set -eu

          STATUS="$(git status)"
          echo "$STATUS"

          # grep will exit non-zero if the target message isn't found,
          # and `set -e` above will cause the step to fail.
          echo "$STATUS" | grep 'nothing to commit, working tree clean'
